apiVersion: "etcd.coreos.com/v1beta1"
kind: "Cluster"
metadata:
  name: "example"
spec:
  size: 3
  backup:
    # short snapshot interval for testing, do not use this in production!
    backupIntervalInSecond: 30
    maxBackups: 5
    storageType: "PersistentVolume"
    pv:
      volumeSizeInMB: 512
    cleanupBackupsOnClusterDelete: true
  TLS:
    static:
      member:
        peerSecret: etcd-peer-tls
        serverSecret: etcd-server-tls
      operatorSecret: etcd-client-tls

