apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdBackup"
metadata:
  name: example-etcd-cluster
spec:
  clusterName: example-etcd-cluster
  storageType: S3
  s3:
    s3Bucket: <s3-bucket-name>
    awsSecret: <aws-secret>
